# Generated by Django 5.0.4 on 2024-05-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='data_hora_pet',
            field=models.CharField(max_length=50),
        ),
    ]
