# Generated by Django 5.0.4 on 2024-05-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_alter_animal_data_hora_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='castrado_pet',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo_pet',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status_pet',
            field=models.CharField(max_length=11),
        ),
    ]
