# Generated by Django 5.0.4 on 2024-05-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0006_alter_animal_imagem_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='castrado_pet',
            field=models.CharField(max_length=3, verbose_name='Castrado:'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='contato_pet',
            field=models.CharField(max_length=20, verbose_name='Contato:'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='data_hora_pet',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='detalhes_pet',
            field=models.CharField(max_length=280, verbose_name='Detalhes:'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='endereco_pet',
            field=models.CharField(max_length=50, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_pet',
            field=models.CharField(max_length=20, verbose_name='Idade:'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagem_pet',
            field=models.ImageField(upload_to='media', verbose_name='Foto do animal:'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome_pet',
            field=models.CharField(max_length=20, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca_pet',
            field=models.CharField(max_length=20, verbose_name='Raça:'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo_pet',
            field=models.CharField(max_length=5, verbose_name='Sexo:'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status_pet',
            field=models.CharField(max_length=11, verbose_name='Situação:'),
        ),
    ]
