# Generated by Django 5.0.4 on 2024-05-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=20)),
                ('nome_pet', models.CharField(max_length=20)),
                ('raca_pet', models.CharField(max_length=20)),
                ('idade_pet', models.CharField(max_length=20)),
                ('sexo_pet', models.CharField(max_length=20)),
                ('castrado_pet', models.CharField(max_length=20)),
                ('endereco_pet', models.CharField(max_length=50)),
                ('contato_pet', models.CharField(max_length=20)),
                ('status_pet', models.CharField(max_length=100)),
                ('detalhes_pet', models.CharField(max_length=100)),
                ('imagem_pet', models.ImageField(upload_to='')),
                ('data_hora_pet', models.DateTimeField()),
            ],
        ),
    ]
