# Generated by Django 5.0.4 on 2024-05-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0003_alter_animal_castrado_pet_alter_animal_sexo_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='detalhes_pet',
            field=models.CharField(max_length=280),
        ),
    ]
