# Generated by Django 5.0.4 on 2024-05-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0004_alter_animal_detalhes_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem_pet',
            field=models.ImageField(upload_to='img'),
        ),
    ]
