# Generated by Django 5.0.4 on 2024-05-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0007_alter_animal_castrado_pet_alter_animal_contato_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='data_hora_pet',
            field=models.CharField(max_length=50),
        ),
    ]
