# Generated by Django 5.0.4 on 2024-05-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0009_alter_animal_data_hora_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='data_hora_pet',
            field=models.CharField(max_length=50, verbose_name='Data da ocorrência:'),
        ),
    ]
