# Generated by Django 5.0.4 on 2024-05-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0011_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='detalhes_pet',
            new_name='detalhes_evento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='imagem_pet',
            new_name='imagem_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(default='local', max_length=20, verbose_name='Local:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.CharField(max_length=20, verbose_name='Data:'),
        ),
    ]
